name: Build and local test

on:
  push:
    branches: [ "base", "multimodule" ]
  pull_request:
    branches: [ "base", "multimodule" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build debug
      run: ./gradlew assembleDebug --stacktrace
      
    - name: Run local tests
      run: ./gradlew testDebug --stacktrace
      
    - name: Upload build outputs (APKs)
      uses: actions/upload-artifact@v3
      with:
        name: build-outputs
        path: ./app/build/outputs

    - name: Upload build reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: build-reports
        path: ./app/build/reports

    - name: Clean before running customizer
      run: git clean -fx .

    - name: Run customizer script
      run: bash customizer.sh com.android.blah MyNewModel MyNewApplication

    - name: "Check that customizer ran correctly"
      uses: andstor/file-existence-action@v2
      with:
        files: "app/src/main/java/com/android/blah/MyNewApplication.kt"
        fail: false

    - name: "Check that customizer removed all unnecessary files"
      id: customizer_rm
      uses: andstor/file-existence-action@v2
      with:
        files: ".git/config"
        fail: false
    - name: "Fail if unnecessary files were not deleted"
      if: steps.customizer_rm.outputs.files_exists == 'true'
      run: exit 1
